version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: sg_database
    ports: 
      - "$DB_PORT:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: sgb_wordpress
    volumes:
      - .:/var/www/html/wp-content/  
    ports:
      - "$WP_PORT:80"
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
volumes:
    db_data: {}